# Generated by Django 3.1.7 on 2021-05-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]

